### ISSUE TITLE
搜索单曲 搜索专辑 LUD-意外错误

### ISSUE THREAD

**Issue by RyanWooG** [MucheXD/CloudMusicDownloader#1]
搜索单曲 搜索专辑 LUD-意外错误
点击搜索按钮出现下面窗口
![image](https://user-images.githubusercontent.com/105183776/199208940-57f44902-14e5-4209-8ce8-a830cd559739.png)

**Comment by MucheXD** [comment]
事实上，这个问题是已知的，因为此功能尚未开发且暂时没有开发计划。如果你浏览源代码就可以看出，这个操作函数仅仅只是被预留在那，没有实质性的功能代码。同时，由于这个项目(LUD)仅仅是一个个人向项目，且已经进入生命周期尾声，因此即使在将来也不大可能完善该功能。对您造成的不便致歉。

**Comment by MucheXD** [comment]
事实上，这个问题是已知的，因为这个功能尚未完成。如果不出意外，我们将在下一个版本更新此内容。

**Comment by MucheXD** [comment]
事实上，这个问题是已知的，因为这个功能尚未完成。如果不出意外，我们将在下一个版本更新此内容。

**Comment by MucheXD** [comment]
事实上，这个问题是已知的，因为这个功能暂时无法完成。网易云API目前不允许我们在未登录的情况下获取专辑信息，以下附失败的请求包（部分信息已隐藏）。
````
GET: http://music.163.com/api/album/1*******7
Response:
{"code":-462,"data":{"actionCode":"1*****3","verifyType":50,"verifyId":1*****1,"verifyUrl":"","blockText":"绑定手机后，可进行下一步操作哦~","verifyToken":null,"btnText":"","orpheusUrl":"","frontRuleIds":[1*****3],"params":{"event_id":"003**************945","sign":"df5**************************2ad"},"url":null},"message":"请绑定手机后再试哦~"}
````
如果我们加入登录功能，那么此程序也就失去了其初衷，因此我们不打算修复此问题。
