### ISSUE TITLE
下载歌曲报错, 提示无法写入文件

### ISSUE THREAD

**Issue by dyxcloud** [MucheXD/CloudMusicDownloader#2]
歌曲名: Another Rain (From "Halo 3: ODST")
猜测是生成的文件夹不合法?

<img width="482" alt="Snipaste_2024-02-24_13-15-53" src="https://github.com/MucheXD/CloudMusicDownloader/assets/31332427/7f2cb86d-9f1d-4afe-949d-d4bd37b6d203">

**Comment by MucheXD** [comment]
您几乎猜对了！
事实上，发生这个错误的原因是Windows平台下不允许使用"\"作为文件名称的一部分，而程序在创建文件时会使用歌曲名称作为文件名，因此导致文件创建失败。
很显然，这完全是MucheXD的失误，因为当时在编码时未考虑到歌名中包含反斜杠的情况。为给您带来的不便表示抱歉！＞﹏＜
虽然如此，由于MucheXD最近很忙，所以不大可能在近期修复该Bug。

**Comment by MucheXD** [comment]
您的ISSUE已经处理！
问题发生在 workWidgets->LINE<836> : 使用正则表达式时忽略了反斜杠的转义作用，导致字符替换"\"未生效。
您的ISSUE已经在下个版本修复。
衷心感谢您的ISSUE！ο(=•ω＜=)ρ
